# REQUIRED CONFIG
BOT_TOKEN = ""
OWNER_ID = 0
TELEGRAM_API = 0
TELEGRAM_HASH = ""
DATABASE_URL = ""


# OPTIONAL CONFIG
DEFAULT_LANG = "en"
TG_PROXY = None
USER_SESSION_STRING = ""
CMD_SUFFIX = ""
STATUS_LIMIT = 10
DEFAULT_UPLOAD = "rc"
STATUS_UPDATE_INTERVAL = 15
EXCLUDED_EXTENSIONS = ""
INCOMPLETE_TASK_NOTIFIER = False
NAME_SWAP = ""
FFMPEG_CMDS = {}
UPLOAD_PATHS = {}


# Leech
LEECH_SPLIT_SIZE = 0
AS_DOCUMENT = False
EQUAL_SPLITS = False
MEDIA_GROUP = False
USER_TRANSMISSION = True
HYBRID_LEECH = True
LEECH_PREFIX = ""
LEECH_SUFFIX = ""
LEECH_FONT = "B"
LEECH_CAPTION = ""
LEECH_THUMBNAIL = ""


# Bot Settings
BOT_PM = False
SET_COMMANDS = True
TIMEZONE = "Asia/Kolkata"

# Telegraph
AUTHOR_NAME = ""
AUTHOR_URL = ""


# Queueing system
QUEUE_ALL = 0
QUEUE_DOWNLOAD = 0
QUEUE_UPLOAD = 0


# Task Limits
DIRECT_LIMIT = 0
MEGA_LIMIT = 0
GD_DL_LIMIT = 0
CLONE_LIMIT = 0
LEECH_LIMIT = 0
EXTRACT_LIMIT = 0
ARCHIVE_LIMIT = 0
STORAGE_LIMIT = 0
